// Single source of truth for enums used across backend + frontends.
// Generated by shared/sync-from-backend.js — do not edit by hand.
// Backend's canonical copy lives at backend/src/common/enums/index.ts.


export enum UserRole {
  BUYER = 'BUYER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPS_MANAGER = 'OPS_MANAGER',
  OPS_STAFF = 'OPS_STAFF',
  AGENT = 'AGENT',
}

export enum UserStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  PENDING_ADMIN_APPROVAL = 'PENDING_ADMIN_APPROVAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
  BLACKLISTED = 'BLACKLISTED',
}

export enum AccountType {
  INDIVIDUAL = 'INDIVIDUAL',
  BUSINESS = 'BUSINESS',
  FUEL_STATION = 'FUEL_STATION',
}

export enum ProductCategory {
  BUILDING_MATERIALS = 'BUILDING_MATERIALS',
  FOOD_BEVERAGES = 'FOOD_BEVERAGES',
  PETROLEUM = 'PETROLEUM',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DISCONTINUED = 'DISCONTINUED',
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  DISPATCHED = 'DISPATCHED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  PAY_AHEAD = 'PAY_AHEAD',
  POD = 'POD',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentGatewayStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum BlacklistType {
  NIN = 'NIN',
  BVN = 'BVN',
  PHONE = 'PHONE',
  DEVICE_ID = 'DEVICE_ID',
  IP = 'IP',
}

export enum NotificationType {
  SMS = 'SMS',
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
